/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu06@inf.ald
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        graphicMenuItem = new javax.swing.JMenuItem();
        agentsMenuItem = new javax.swing.JMenuItem();
        operationsMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu.setText("File");

        graphicMenuItem.setText("Gestionar Gráfica...");
        jMenu.add(graphicMenuItem);

        agentsMenuItem.setText("Gestionar Agentes...");
        jMenu.add(agentsMenuItem);

        operationsMenuItem.setText("Gestionar Operaciones...");
        jMenu.add(operationsMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setText("Quit");
        jMenu.add(quitMenuItem);

        menuBar.add(jMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void AgentsMenuItemActionListener(ActionListener al) {
        this.agentsMenuItem.addActionListener(al);
    }
    
    public void GraphicsMenuItem(ActionListener al) {
        this.graphicMenuItem.addActionListener(al);
    }
    
    public void OperationsMenutItem(ActionListener al) {
        this.operationsMenuItem.addActionListener(al);
    }
    
    public void QuitMenutItemListener(ActionListener al) {
        this.quitMenuItem.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agentsMenuItem;
    private javax.swing.JMenuItem graphicMenuItem;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem operationsMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    // End of variables declaration//GEN-END:variables
}
